### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by luckman212** [Signynt/link-headers-directly#1]
Hey @Signynt - this is a great little plugin! really cleans up the previews when you have a lot of linked headers.

one small thing, I noticed you updated the plugin to v 1.0.2 but the `maniifest.json` still indicates 1.0.0

**Comment by Signynt** [comment]
Hey @luckman212 - I'm glad you enjoy it!
Thanks for the hint, I totally forgot that I need to update the version number in the manifest, it's fixed now.
